# Conda environment configuration file

name: airlines
dependencies:
  - python=3.7.7
  - ipykernel
  - luigi=3.0.0
  - numpy=1.19.1
  - pandas=1.1.0
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - tqdm=4.48.2
